obj-$(CONFIG_ASPEED_HACE) += aspeed_hace.o
obj-$(CONFIG_ASPEED_ACRY) += aspeed_acry.o
obj-$(CONFIG_ASPEED_RSSS) += aspeed_rsss.o
obj-$(CONFIG_ASPEED_CPTRA_SHA) += cptra_sha.o
obj-$(CONFIG_SPL_ASPEED_MHMAC) += aspeed_mhmac.o
obj-y += cptra_ecdsa.o
obj-$(CONFIG_ASPEED_CPTRA_IPC_ECDSA) += cptra_ipc_ecdsa.o
obj-$(CONFIG_ASPEED_CPTRA_IPC_SHA) += cptra_ipc_sha.o