/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Copyright (c) Aspeed Technology Inc.
 */
#ifndef _ASM_ARCH_LTPI_AST2700_H
#define _ASM_ARCH_LTPI_AST2700_H

#define LTPI_LINK_MANAGE_ST_REG			0x108
#define   LTPI_LINK_PARTNER_AST1700		BIT(24)
#define   LTPI_LINK_MANAGE_ST			GENMASK(3, 0)
#define     LTPI_LINK_MANAGE_ST_DETECT_ALIGN	0
#define     LTPI_LINK_MANAGE_ST_DETECT		1
#define     LTPI_LINK_MANAGE_ST_SPEED		2
#define     LTPI_LINK_MANAGE_ST_WAIT_PLL_SET	3
#define     LTPI_LINK_MANAGE_ST_ADV_ALIGN	4
#define     LTPI_LINK_MANAGE_ST_ADV		5
#define     LTPI_LINK_MANAGE_ST_CONFIG_ACC	6
#define     LTPI_LINK_MANAGE_ST_OP		7

#define LTPI_ADDR_REMAP_REG0			0x124
#define   REMAP_ENTRY1				GENMASK(25, 16)
#define   REMAP_ENTRY0				GENMASK(9, 0)
#define LTPI_ADDR_REMAP_REG1			0x128
#define   REMAP_ENTRY3				GENMASK(25, 16)
#define   REMAP_ENTRY2				GENMASK(9, 0)

#define LTPI_REMOTE_AST1700_IOD_SPACE		(0x14000000 >> 26)
#define LTPI_REMOTE_AST1700_SPI2_SPACE		(0x280000000U >> 26)

int ltpi_init(void);
#endif
