/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Copyright (c) Aspeed Technology Inc.
 */
#ifndef _ASM_ARCH_MMC_AST2700_H

#define MMC_CLK_DRIVING_REG	(ASPEED_CPU_SCU_BASE + 0x480)
#define MMC_CMD_DRIVING_REG	(ASPEED_CPU_SCU_BASE + 0x484)
#define MMC_DAT0_DRIVING_REG	(ASPEED_CPU_SCU_BASE + 0x488)
#define MMC_DAT1_DRIVING_REG	(ASPEED_CPU_SCU_BASE + 0x48c)
#define MMC_DAT2_DRIVING_REG	(ASPEED_CPU_SCU_BASE + 0x490)
#define MMC_DAT3_DRIVING_REG	(ASPEED_CPU_SCU_BASE + 0x494)
#define MMC_CD_DRIVING_REG	(ASPEED_CPU_SCU_BASE + 0x498)
#define MMC_WP_DRIVING_REG	(ASPEED_CPU_SCU_BASE + 0x49c)
#define MMC_DAT4_DRIVING_REG	(ASPEED_CPU_SCU_BASE + 0x4a0)
#define MMC_DAT5_DRIVING_REG	(ASPEED_CPU_SCU_BASE + 0x4a4)
#define MMC_DAT6_DRIVING_REG	(ASPEED_CPU_SCU_BASE + 0x4a8)
#define MMC_DAT7_DRIVING_REG	(ASPEED_CPU_SCU_BASE + 0x4ac)

int emmc_init(void);
int emmc_load_image(u32 *src, u32 *dest, u32 len);

#endif
