obj-$(CONFIG_TARGET_ASPEED_AST2700) += ibex_ast2700.o   \
					stor.o          \
					spi.o           \
					recovery.o      \
					recovery_uart.o \
					pll.o           \
					wdt.o           \
					abr.o           \
					ssp_tsp.o       \
					extrst.o

obj-$(CONFIG_ASPEED_FPGA) += fpga_phy.o
obj-$(CONFIG_ASPEED_EXPORT_LOADER) += loader.o