obj-$(CONFIG_TARGET_ASPEED_AST2700) += ibex_ast2700.o sdram_ast2700.o sdram_phy.o vga.o sli.o ltpi.o stor.o spi.o recovery.o pll.o wdt.o abr.o fmc_hdr.o ssp_tsp.o
obj-$(CONFIG_SPL_SLI_AST2700) += sli.o
obj-$(CONFIG_ASPEED_FPGA) += fpga_phy.o
