obj-$(CONFIG_AST2600_CMD_OTP) += otp_ast2600.o
obj-$(CONFIG_AST2700_CMD_OTP) += otp_ast2700.o
obj-$(CONFIG_AST2700_CMD_FLASH_STRAP) += flash_strap.o
obj-$(CONFIG_AST2700_CMD_LTPI) += ltpi/ltpi.o
obj-$(CONFIG_AST2600_CMD_DPTEST) += dptest_2600.o
obj-$(CONFIG_AST2700_CMD_DPTEST) += dptest_2700.o
