/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Copyright (C) ASPEED Technology Inc.
 */

/* come from linux kernel */

//cpu die
#define ASPEED_CLK_GATE_MCLK		0
#define ASPEED_CLK_GATE_ECLK		1
#define ASPEED_CLK_GATE_GCLK		2
#define ASPEED_CLK_GATE_VCLK		3
#define ASPEED_CLK_GATE_BCLK		4
#define ASPEED_CLK_GATE_D1CLK		5
#define ASPEED_CLK_GATE_REFCLK		6
#define ASPEED_CLK_GATE_USBCLK		7
#define ASPEED_CLK_GATE_RSV8CLK		8
#define ASPEED_CLK_GATE_USB1CLK		9
#define ASPEED_CLK_GATE_D2CLK		10
#define ASPEED_CLK_GATE_RSV11CLK	11
#define ASPEED_CLK_GATE_RSV12CLK	12
#define ASPEED_CLK_GATE_YCLK		13
#define ASPEED_CLK_GATE_USB2CLK		14
#define ASPEED_CLK_GATE_UART5CLK	15
#define ASPEED_CLK_GATE_SLICLK		16
#define ASPEED_CLK_GATE_DLCLK		17
#define ASPEED_CLK_GATE_RSV18CLK	18
#define ASPEED_CLK_GATE_RSV19CLK	19
#define ASPEED_CLK_GATE_CRT1CLK		20
#define ASPEED_CLK_GATE_CRT2CLK		21
#define ASPEED_CLK_GATE_DVCLK		22
#define ASPEED_CLK_GATE_ECCCLK		23
#define ASPEED_CLK_GATE_RSACLK		24
#define ASPEED_CLK_GATE_RVASCLK		25
#define ASPEED_CLK_GATE_UFSCLK		26
#define ASPEED_CLK_GATE_EMMCCLK		27

/* reserved 28 ~ 31*/

//io die
#define ASPEED_CLK_GATE_L0CLK		(32 + 0)
#define ASPEED_CLK_GATE_L1CLK		(32 + 1)
#define ASPEED_CLK_GATE_ESPI0CLK	(32 + 2)
#define ASPEED_CLK_GATE_ESPI1CLK	(32 + 3)
#define ASPEED_CLK_GATE_SDCLK		(32 + 4)
#define ASPEED_CLK_GATE_RSV5CLK		(32 + 5)
#define ASPEED_CLK_GATE_SDEXTCLK	(32 + 6)
#define ASPEED_CLK_GATE_LPCHCLK		(32 + 7)
#define ASPEED_CLK_GATE_MAC0CLK		(32 + 8)
#define ASPEED_CLK_GATE_MAC1CLK		(32 + 9)
#define ASPEED_CLK_GATE_MAC2CLK		(32 + 10)
#define ASPEED_CLK_GATE_UART1CLK	(32 + 11)
#define ASPEED_CLK_GATE_UART2CLK	(32 + 12)
#define ASPEED_CLK_GATE_UART3CLK	(32 + 13)
#define ASPEED_CLK_GATE_UART4CLK	(32 + 14)
#define ASPEED_CLK_GATE_I2CCLK		(32 + 15)
#define ASPEED_CLK_GATE_I3C0CLK		(32 + 16)
#define ASPEED_CLK_GATE_I3C1CLK		(32 + 17)
#define ASPEED_CLK_GATE_I3C2CLK		(32 + 18)
#define ASPEED_CLK_GATE_I3C3CLK		(32 + 19)
#define ASPEED_CLK_GATE_I3C4CLK		(32 + 20)
#define ASPEED_CLK_GATE_I3C5CLK		(32 + 21)
#define ASPEED_CLK_GATE_I3C6CLK		(32 + 22)
#define ASPEED_CLK_GATE_I3C7CLK		(32 + 23)
#define ASPEED_CLK_GATE_I3C8CLK		(32 + 24)
#define ASPEED_CLK_GATE_I3C9CLK		(32 + 25)
#define ASPEED_CLK_GATE_I3C10CLK	(32 + 26)
#define ASPEED_CLK_GATE_I3C11CLK	(32 + 27)
#define ASPEED_CLK_GATE_I3C12CLK	(32 + 28)
#define ASPEED_CLK_GATE_I3C13CLK	(32 + 29)
#define ASPEED_CLK_GATE_I3C14CLK	(32 + 30)
#define ASPEED_CLK_GATE_I3C15CLK	(32 + 31)
#define ASPEED_CLK_GATE_UART6CLK	(64 + 0)
#define ASPEED_CLK_GATE_UART7CLK	(64 + 1)
#define ASPEED_CLK_GATE_UART8CLK	(64 + 2)
#define ASPEED_CLK_GATE_UART9CLK	(64 + 3)
#define ASPEED_CLK_GATE_UART10CLK	(64 + 4)
#define ASPEED_CLK_GATE_UART11CLK	(64 + 5)
#define ASPEED_CLK_GATE_UART12CLK	(64 + 6)
#define ASPEED_CLK_GATE_UART13CLK	(64 + 7)
#define ASPEED_CLK_GATE_FSICLK		(64 + 8)
#define ASPEED_CLK_GATE_LPTITXCLK	(64 + 9)
#define ASPEED_CLK_GATE_LPTICLK		(64 + 10)

#define ASPEED_CLK_APLL			(96 + 0)
#define ASPEED_CLK_EPLL			(96 + 1)
#define ASPEED_CLK_DPLL			(96 + 2)
#define ASPEED_CLK_HPLL			(96 + 3)
#define ASPEED_CLK_AHB			(96 + 4)
#define ASPEED_CLK_APB1			(96 + 5)
#define ASPEED_CLK_APB2			(96 + 6)
#define ASPEED_CLK_UART			(96 + 7)
#define ASPEED_CLK_SDIO			(96 + 8)
#define ASPEED_CLK_ECLK			(96 + 9)
#define ASPEED_CLK_ECLK_MUX		(96 + 10)
#define ASPEED_CLK_LHCLK		(96 + 11)
#define ASPEED_CLK_MAC			(96 + 12)
#define ASPEED_CLK_BCLK			(96 + 13)
#define ASPEED_CLK_MPLL			(96 + 14)
#define ASPEED_CLK_24M			(96 + 15)
#define ASPEED_CLK_EMMC			(96 + 16)
#define ASPEED_CLK_UARTX		(96 + 17)
#define ASPEED_CLK_HUARTX		(96 + 18)
