obj-$(CONFIG_ASPEED_AST2500_PINCTRL) += pinctrl_ast2500.o
obj-$(CONFIG_ASPEED_AST2600_PINCTRL) += pinctrl_ast2600.o
obj-$(CONFIG_ASPEED_AST2700_PINCTRL) += pinctrl_ast2700_soc0.o pinctrl_ast2700_soc1.o
