# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2016 Google, Inc
#

obj-$(CONFIG_ASPEED_AST2500) += clk_ast2500.o
obj-$(CONFIG_ASPEED_AST2600) += clk_ast2600.o
obj-$(CONFIG_ASPEED_AST2700) += clk_ast2700_soc0.o clk_ast2700_soc1.o
obj-$(CONFIG_TARGET_ASPEED_AST2700BMCU) += clk_ast2700_soc0.o clk_ast2700_soc1.o
